version: 0.0
os: linux
files:
  - source: index.html
    destination: /var/www/html
permissions:
  - object: /var/www/html
    pattern: "*.html"
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - file
hooks:
 BeforeInstall:
   - location: scripts/install.sh
     timeout: 3600
     runas: root
 ApplicationStart:
   - location: scripts/start.sh
     timeout: 3600
     runas: root
